//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_dio.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wpf_dio.Langs.lang - Copy", typeof(lang___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod:.
        /// </summary>
        internal static string InfoWindow_lblHomeCode {
            get {
                return ResourceManager.GetString("InfoWindow.lblHomeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zemlja:.
        /// </summary>
        internal static string InfoWindow_lblHomeCountry {
            get {
                return ResourceManager.GetString("InfoWindow.lblHomeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerješeno:.
        /// </summary>
        internal static string InfoWIndow_lblHomeDraws {
            get {
                return ResourceManager.GetString("InfoWIndow.lblHomeDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika golova:.
        /// </summary>
        internal static string InfoWindow_lblHomeGoalsDiff {
            get {
                return ResourceManager.GetString("InfoWindow.lblHomeGoalsDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi Zabijeni.
        /// </summary>
        internal static string InfoWIndow_lblHomeGoalsScored {
            get {
                return ResourceManager.GetString("InfoWIndow.lblHomeGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi Uzeti:.
        /// </summary>
        internal static string InfoWindow_lblHomeGoalsTaken {
            get {
                return ResourceManager.GetString("InfoWindow.lblHomeGoalsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izgubili:.
        /// </summary>
        internal static string InfoWindow_lblHomeLosses {
            get {
                return ResourceManager.GetString("InfoWindow.lblHomeLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrali:.
        /// </summary>
        internal static string InfoWindow_lblHomePlayed {
            get {
                return ResourceManager.GetString("InfoWindow.lblHomePlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjedili:.
        /// </summary>
        internal static string InfoWIndow_lblHomeWins {
            get {
                return ResourceManager.GetString("InfoWIndow.lblHomeWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod:.
        /// </summary>
        internal static string InfoWindow_lblOtherCode {
            get {
                return ResourceManager.GetString("InfoWindow.lblOtherCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zemlja:.
        /// </summary>
        internal static string InfoWindow_lblOtherCountry {
            get {
                return ResourceManager.GetString("InfoWindow.lblOtherCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nerješeno:.
        /// </summary>
        internal static string InfoWIndow_lblOtherDraws {
            get {
                return ResourceManager.GetString("InfoWIndow.lblOtherDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika golova.
        /// </summary>
        internal static string InfoWindow_lblOtherGoalsDiff {
            get {
                return ResourceManager.GetString("InfoWindow.lblOtherGoalsDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi Zabijeni.
        /// </summary>
        internal static string InfoWIndow_lblOtherGoalsScored {
            get {
                return ResourceManager.GetString("InfoWIndow.lblOtherGoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golovi Uzeti:.
        /// </summary>
        internal static string InfoWindow_lblOtherGoalsTaken {
            get {
                return ResourceManager.GetString("InfoWindow.lblOtherGoalsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izgubili:.
        /// </summary>
        internal static string InfoWindow_lblOtherLosses {
            get {
                return ResourceManager.GetString("InfoWindow.lblOtherLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrali:.
        /// </summary>
        internal static string InfoWindow_lblOtherPlayed {
            get {
                return ResourceManager.GetString("InfoWindow.lblOtherPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjedili:.
        /// </summary>
        internal static string InfoWIndow_lblOtherWins {
            get {
                return ResourceManager.GetString("InfoWIndow.lblOtherWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacije.
        /// </summary>
        internal static string MainWindow_Bars_Representation {
            get {
                return ResourceManager.GetString("MainWindow.Bars.Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        internal static string MainWindow_Bars_Settings {
            get {
                return ResourceManager.GetString("MainWindow.Bars.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igrači Tima.
        /// </summary>
        internal static string MainWindow_Bars_TeamMembers {
            get {
                return ResourceManager.GetString("MainWindow.Bars.TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Više Informacija.
        /// </summary>
        internal static string MainWindow_Reps_btnInfo {
            get {
                return ResourceManager.GetString("MainWindow.Reps.btnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tim 1:.
        /// </summary>
        internal static string MainWindow_Reps_lblHomeTeam {
            get {
                return ResourceManager.GetString("MainWindow.Reps.lblHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tim 2:.
        /// </summary>
        internal static string MainWindow_Reps_lblOtherTeam {
            get {
                return ResourceManager.GetString("MainWindow.Reps.lblOtherTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultat.
        /// </summary>
        internal static string MainWindow_Reps_lblScore {
            get {
                return ResourceManager.GetString("MainWindow.Reps.lblScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string MainWindow_Settings_btnConfirm {
            get {
                return ResourceManager.GetString("MainWindow.Settings.btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string MainWindow_Settings_lblLang {
            get {
                return ResourceManager.GetString("MainWindow.Settings.lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacija.
        /// </summary>
        internal static string MainWindow_Settings_lblRep {
            get {
                return ResourceManager.GetString("MainWindow.Settings.lblRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija.
        /// </summary>
        internal static string MainWindow_Settings_lblRes {
            get {
                return ResourceManager.GetString("MainWindow.Settings.lblRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženska.
        /// </summary>
        internal static string MainWindow_Settings_rbRepF {
            get {
                return ResourceManager.GetString("MainWindow.Settings.rbRepF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muška.
        /// </summary>
        internal static string MainWindow_Settings_rbRepM {
            get {
                return ResourceManager.GetString("MainWindow.Settings.rbRepM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        internal static string StartingWindow_btnConfirm {
            get {
                return ResourceManager.GetString("StartingWindow.btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik:.
        /// </summary>
        internal static string StartingWIndow_lblLang {
            get {
                return ResourceManager.GetString("StartingWIndow.lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put:.
        /// </summary>
        internal static string StartingWindow_lblPath {
            get {
                return ResourceManager.GetString("StartingWindow.lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprezentacija:.
        /// </summary>
        internal static string StartingWindow_lblPrvenstvo {
            get {
                return ResourceManager.GetString("StartingWindow.lblPrvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija.
        /// </summary>
        internal static string StartingWindow_lblRes {
            get {
                return ResourceManager.GetString("StartingWindow.lblRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ženska.
        /// </summary>
        internal static string StartingWindow_rbPrvenstvoF {
            get {
                return ResourceManager.GetString("StartingWindow.rbPrvenstvoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muška.
        /// </summary>
        internal static string StartingWindow_rbPrvenstvoM {
            get {
                return ResourceManager.GetString("StartingWindow.rbPrvenstvoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
